--22127405
--Trần Minh Thư
--H3C6

USE MASTER
GO 
IF DB_ID('QLCH') IS NOT NULL
DROP DATABASE QLCH
GO
CREATE DATABASE QLCH
GO
USE QLCH

CREATE TABLE SANPHAM
(
	MASP CHAR(5),
	MALOAI INT,
	TENSP NVARCHAR(50),
	SOLUONGTON INT,
	DONGIA INT

	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP, MALOAI)
)

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4),
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(50),
	KHPHUTHUOC CHAR(4)

	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
)

CREATE TABLE MUAHANG
(
	MAKH CHAR(4),
	MASP CHAR(5),
	MALOAI INT,
	NGAYMUA DATE, 
	SOLUONG INT,
	DONGIA INT,
	THANHTIEN INT

	CONSTRAINT PK_MUAHANG PRIMARY KEY (MAKH, MASP, MALOAI, NGAYMUA)
)

ALTER TABLE KHACHHANG
ADD
	CONSTRAINT PK_PT_KH FOREIGN KEY (KHPHUTHUOC)
	REFERENCES KHACHHANG

ALTER TABLE MUAHANG
ADD 
	CONSTRAINT PK_MH_SP FOREIGN KEY (MASP, MALOAI)
	REFERENCES SANPHAM,
	CONSTRAINT PK_MH_KH FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG

INSERT SANPHAM(MASP, MALOAI, TENSP, SOLUONGTON, DONGIA) VALUES
('SP001', 1, N'Fruit Me Up Nước Táo Dinh Dưỡng', 120, 41600),
('SP002', 1, N'Nước ép trái cây hữu cơ sạch Yujachio', 98, 31450),
('SP001', 2, N'Sữa uống dinh dưỡng Optimum Gold', 100, 63640),
('SP003', 2, N'Sữa uống dinh dưỡng Dielac Grow Plus', 50, 68800)

SET DATEFORMAT DMY
INSERT KHACHHANG(MAKH, HOTEN, NGAYSINH, DIACHI) VALUES
('0001', N'Nguyễn Thị Minh', '12-02-2000', N'123 Vườn Lài, Quận Tân Phú'),
('0002', N'Trần Trung Nghĩa', '23-11-2009', N'45 Phú Thọ Hòa, Quận Tân Phú'),
('0003', N'Vũ Ánh Nguyệt', '22-11-1997', N'11 Võ Văn Ngân, Quận Thủ Đức'),
('0004', N'Trần Thu Phương', '11-11-2007', N'11 Nguyễn Trãi, Quận 5'),
('0005', N'Nguyễn Minh Hùng', '10-01-2000', null)

INSERT MUAHANG(MAKH, MASP, MALOAI, NGAYMUA, SOLUONG, DONGIA) VALUES
('0001', 'SP001', 1, '12-02-2019', 30, 41600),
('0001', 'SP002', 1, '12-02-2019', 20, 31450),
('0004', 'SP001', 1, '06-06-2021', 10, 41600),
('0005', 'SP001', 2, '07-03-2022', 5, 63640),
('0002', 'SP002', 1, '07-03-2022', 5, 31450),
('0003', 'SP003', 2, '07-03-2022', 5, 68800)

UPDATE KHACHHANG
SET KHPHUTHUOC = '0002'
WHERE MAKH = '0001'
UPDATE KHACHHANG
SET KHPHUTHUOC = '0004'
WHERE MAKH = '0002'
UPDATE KHACHHANG
SET KHPHUTHUOC = NULL
WHERE MAKH = '0003' AND MAKH = '0004' AND MAKH = '0005'

UPDATE MUAHANG
SET THANHTIEN = SOLUONG * DONGIA

SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG
SELECT * FROM MUAHANG

--TRUYVAN
--C4
SELECT DISTINCT SP.MASP, SP.TENSP, MH.SOLUONG, MH.DONGIA, MH.THANHTIEN
FROM SANPHAM SP JOIN MUAHANG MH ON SP.MASP = MH.MASP AND SP.MALOAI = MH.MALOAI
				JOIN KHACHHANG KH ON KH.MAKH = MH.MAKH
WHERE KH.DIACHI LIKE '%Tân Phú' AND YEAR(MH.NGAYMUA) = 2019 AND MONTH(MH.NGAYMUA) = '02'
--TRƯỜNG HỢP CÙNG MỘT KHÁCH HÀNG, MUA CÙNG LOẠI SP (CÙNG LOẠI, CÙNG MÃ SẢN PHẨM) NHƯNG KHÁC NGÀY NÊN PHẢI XÀI DISTINCT

--C5
SELECT KH.MAKH, KH.HOTEN, KH.NGAYSINH, KH.DIACHI, KH.KHPHUTHUOC, SUM(MH.SOLUONG) 'SLSP', SUM(MH.THANHTIEN) 'THD'
FROM SANPHAM SP JOIN MUAHANG MH ON SP.MASP = MH.MASP AND SP.MALOAI = MH.MALOAI
				JOIN KHACHHANG KH ON KH.MAKH = MH.MAKH
GROUP BY KH.MAKH, KH.MAKH, KH.HOTEN, KH.NGAYSINH, KH.DIACHI, KH.KHPHUTHUOC
