CREATE DATABASE KT_1A_QLCT

USE KT_1A_QLCT

CREATE TABLE EMPLOYEE
(
	FNAME CHAR(10),
	MINIT CHAR(1),
	LNAME CHAR(10),
	SSN CHAR(9),
	BDATE DATE,
	ADDRESS_ VARCHAR(50),
	SEX CHAR(1), 
	SALARY INT,
	SUPER_SSN CHAR(9),
	DNO INT
	
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY SSN
)

CREATE TABLE DEPARTMENT
(
	DNAME CHAR(20),
	DNUMBER INT,
	MGR_SSN CHAR(9),
	MGR_START_DATE DATE

	CONSTRAINT PK_DEPARTMENT PRIMARY KEY DEPARTMENT
)

CREATE TABLE DEPT_LOCATIONS
(
	DNUMBER INT,
	DLOCATION CHAR(10)

	CONSTRAINT PK_DL PRIMARY KEY (DNUMBER, DLOCATION)
)

CREATE TABLE PROJECT
(
	PNAME CHAR(20),
	PNUMBER INT,
	PLOCATION CHAR(10),
	DNUM INT

	CONSTRAINT PK_PROJECT PRIMARY KEY (PNUMBER)
)

CREATE TABLE WORKS_ON
(
	ESSN CHAR(9),
	PNO INT,
	HOURS_ FLOAT
	
	CONSTRAINT PK_WO PRIMARY KEY (ESSN, PNO)
)

CREATE TABLE DEPENDENT_
(
	ESSN CHAR(9),
	DEPENDENT_NAME CHAR(10),
	SEX CHAR(1),
	BDATE DATE,
	RELATIONSHIP CHAR(10)

	CONSTRAINT PK_DEPEN PRIMARY KEY (ESSN, DEPENDENT_NAME)
)

ALTER TABLE EMPLOYEE
ADD
	CONSTRAINT FK_E_E_ FOREIGN KEY (SUPER_SSN)
	REFERENCES EMPLOYEE,
	CONSTRAINT FK_E_D FOREIGN KEY (DNO)
	REFERENCES DEPARTMENT

ALTER TABLE DEPARTMENT
ADD
	CONSTRAINT 
	
