USE MASTER
GO
IF DB_ID('MIDTERM_33') IS NOT NULL
	DROP DATABASE MIDTERM_33

GO
CREATE DATABASE MIDTERM_33
GO
USE MIDTERM_33

CREATE TABLE PHONGTHI
(
	IDPHONG CHAR(4),
	IDDIEMTHI CHAR(3),
	CANBO CHAR(5),
	SOBAN INT,
	THIETBI NVARCHAR(50)

	CONSTRAINT PK_PHONGTHI PRIMARY KEY (IDPHONG, IDDIEMTHI)
)

CREATE TABLE THISINH
(
	SBD CHAR(4),
	DIEMTHI CHAR(3),
	HOTEN NVARCHAR(50),
	DIACHI NVARCHAR(50),
	NGAYSINH DATE,
	PHONGTHI CHAR(4),

	CONSTRAINT PK_THISINH PRIMARY KEY (SBD)
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(5),
	TENGV NVARCHAR(50),
	DIACHI NVARCHAR(50),
	VAITRO NVARCHAR(50)

	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)

--THEM KHOA NGOAI
ALTER TABLE PHONGTHI
ADD
	CONSTRAINT FK_PT_GV FOREIGN KEY (CANBO)
	REFERENCES GIAOVIEN

ALTER TABLE THISINH
ADD 
	CONSTRAINT FK_TS_PT FOREIGN KEY (PHONGTHI, DIEMTHI)
	REFERENCES PHONGTHI

SET DATEFORMAT DMY
--THEM GIA TRI
INSERT GIAOVIEN (MAGV, TENGV, DIACHI, VAITRO) VALUES
('GV001', N'Trần Thị Bé', N'31 Nguyễn Xí Q.Bình Thạnh', N'Cán bộ'),
('GV002', N'Nguyễn Minh Tâm', N'2 Trần Hưng Đạo Q5', N'Giám sát'),
('GV003', N'Trần Văn Lí', N'30 Hà Tôn Quyền Q5', N'Cán bộ')

INSERT PHONGTHI (IDPHONG, IDDIEMTHI, CANBO, SOBAN, THIETBI) VALUES
('P001', 'DD1', 'GV001', 25, N'Mic-Loa-Tivi'),
('P002', 'DD1', 'GV002', 30, N'Mic-Loa-Tivi'),
('P001', 'DD2', 'GV003', 15, null)

INSERT THISINH (SBD, DIEMTHI, HOTEN, DIACHI, NGAYSINH, PHONGTHI) VALUES
('0231', 'DD1', N'Nguyễn Quan Tùng', N'TPHCM', '30-11-2000', 'P001'),
('0230', 'DD2', N'Lưu Phi Nam', N'Hải Phòng', '12-02-2000', 'P001'),
('0234', 'DD1', N'Lê Quang Bảo', N'Hà Nội', '13-02-2000', 'P002'),
('0233', 'DD2', N'Hà Ngọc Thúy', N'TPHCM', '24-04-2000', 'P001')

select* from GIAOVIEN
select* from PHONGTHI
select* from THISINH

SELECT PT.IDPHONG, PT.CANBO, COUNT(TS.SBD) 'SLTS'
FROM PHONGTHI PT JOIN THISINH TS ON PT.IDPHONG = TS.PHONGTHI AND PT.IDDIEMTHI = TS.DIEMTHI
GROUP BY PT.IDPHONG, PT.CANBO

SELECT PT.*, GV.TENGV, TS.HOTEN
FROM PHONGTHI PT JOIN THISINH TS ON PT.IDPHONG = TS.PHONGTHI AND PT.IDDIEMTHI = TS.DIEMTHI
				 JOIN GIAOVIEN GV ON PT.CANBO = GV.MAGV
WHERE PT.SOBAN > 15 AND TS.DIACHI = N'Hải Phòng'
