CREATE DATABASE MIDTERM_W5
USE MIDTERM_W5

CREATE TABLE KHACHHANG
(
	MALOAI CHAR(2),
	HOTEN NVARCHAR(50),
	STT INT,
	DIACHI NVARCHAR(50)

	CONSTRAINT PK_KH PRIMARY KEY (MALOAI, STT)
)

CREATE TABLE SACH
(
	MASACH CHAR(4),
	TENSACH NVARCHAR(100),
	SOLUONG INT,
	DONGIA FLOAT,
	MALOAI CHAR(2),
	KHTIEUBIEU INT
	 
	CONSTRAINT PK_SACH PRIMARY KEY (MASACH)
	CONSTRAINT FK_S_KH FOREIGN KEY(MALOAI, KHTIEUBIEU)
	REFERENCES KHACHHANG
)

CREATE TABLE MUAHANG
(
	LOAIKH CHAR(2),
	SOTT INT,
	MASACH CHAR(4),
	NGAYMUA DATE,
	SOLUONG INT,
	DONGIA FLOAT

	CONSTRAINT PK_MH PRIMARY KEY (LOAIKH, SOTT, MASACH)
	CONSTRAINT FK_MH_KH FOREIGN KEY (LOAIKH, SOTT)
	REFERENCES KHACHHANG,
	CONSTRAINT FK_MH_SACH FOREIGN KEY(MASACH)
	REFERENCES SACH
)

INSERT KHACHHANG(MALOAI, STT, HOTEN, DIACHI) VALUES 
('L1',1, N'Nguyễn Thị Minh', N'123 Vườn Lài, Tân Phú'),
('L1', 2, N'Trần Trung Nghĩa', N'45 Phú Thọ Hòa, Tân Phú'),
('L2', 1, N'Vũ Ánh Nguyệt', N'11 Võ Văn Ngân, Thủ Đức')SELECT * FROM MUAHANGSET DATEFORMAT DMYINSERT SACH(MASACH, TENSACH, SOLUONG, DONGIA, MALOAI, KHTIEUBIEU)VALUES('S001', N'Đồi Thỏ', 1000, 97000, 'L1', 1),
('S002', N'Bài giảng cuối cùng', 24, 102000, 'L2', 1)INSERT MUAHANG (LOAIKH, SOTT, MASACH, NGAYMUA, SOLUONG, DONGIA)VALUES('L1', 1, 'S001', '12/2/2009', 30, 90000),
('L1', 2, 'S001', '30/12/2019', 20, 87000),
('L2', 1, 'S002', '6/6/2016' ,10, 100000),
('L1', 2, 'S002', '7/3/2018' ,5, 120000)SELECT KH.*, SUM(SOLUONG * DONGIA) TONGTRIGIAFROM KHACHHANG KH JOIN MUAHANG MH ON MH.LOAIKH = KH.MALOAI AND MH.SOTT = KH.STTGROUP BY KH.MALOAI, KH.DIACHI, KH.HOTEN, KH.STTSELECT KH.*FROM KHACHHANG KH JOIN MUAHANG MH ON MH.LOAIKH = KH.MALOAI AND MH.SOTT = KH.STTWHERE KH.HOTEN LIKE N'Nguyễn %' AND MONTH(NGAYMUA) = 12 AND YEAR(NGAYMUA) = 2009 AND SOLUONG > 10