--TRUY VẤN LỒNG W05

USE QLDETAI
--Q35
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV 
WHERE GV.LUONG >= ALL (SELECT LUONG FROM GIAOVIEN)

--Q36
SELECT *
FROM GIAOVIEN 
WHERE LUONG >= ALL (SELECT LUONG FROM GIAOVIEN)

--Q37
SELECT *
FROM GIAOVIEN 
WHERE LUONG >= ALL (SELECT LUONG FROM GIAOVIEN WHERE MABM = 'HTTT') AND MABM = 'HTTT'

--Q38
SELECT HOTEN
FROM GIAOVIEN
WHERE NGSINH <= ALL (SELECT NGSINH FROM GIAOVIEN WHERE MABM = 'HTTT') AND MABM = 'HTTT'

--Q39
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.MAKHOA = 'CNTT' AND NGSINH >= ALL (SELECT NGSINH FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
				 JOIN KHOA K2 ON BM2.MAKHOA = K2.MAKHOA AND K2.MAKHOA = 'CNTT') 

--Q40
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE GV.LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN)

--Q41
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE (SELECT COUNT(*) FROM GIAOVIEN GV2 
WHERE GV2.LUONG > GV.LUONG AND GV.MABM = GV2.MABM) = 0

--Q42
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT NOT IN (SELECT DT.MADT
				 FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
				 JOIN DETAI DT ON TGDT.MADT = DT.MADT
				 WHERE GV.HOTEN = N'Nguyễn Hoài An')

--Q43
SELECT DT.*, GV.HOTEN
FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
WHERE DT.MADT NOT IN (SELECT DT.MADT
				 FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
				 JOIN DETAI DT ON TGDT.MADT = DT.MADT
				 WHERE GV.HOTEN = N'Nguyễn Hoài An')

--Q44
SELECT DISTINCT GV.HOTEN, GV.MAGV
FROM THAMGIADT TGDT 	
			  JOIN GIAOVIEN GV ON TGDT.MAGV = GV.MAGV 
			  JOIN BOMON BM ON GV.MABM  = BM.MABM
			  JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE GV.MAGV NOT IN (SELECT DISTINCT GV.MAGV
			  FROM THAMGIADT TGDT 	
			  JOIN GIAOVIEN GV ON TGDT.MAGV = GV.MAGV 
			  JOIN BOMON BM ON GV.MABM  = BM.MABM
			  JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
			  WHERE K.MAKHOA = 'CNTT') AND K.MAKHOA = 'CNTT'

--Q45
SELECT DISTINCT HOTEN, MAGV
FROM  GIAOVIEN
WHERE MAGV NOT IN (SELECT DISTINCT GV.MAGV
			  FROM THAMGIADT TGDT 	
			  JOIN GIAOVIEN GV ON TGDT.MAGV = GV.MAGV) 

--Q46
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT LUONG FROM GIAOVIEN WHERE HOTEN = N'Nguyễn Hoài An')

--Q47
SELECT GV.MAGV 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
EXCEPT (
SELECT DISTINCT  MAGV
FROM  GIAOVIEN
WHERE MAGV NOT IN (SELECT DISTINCT GV.MAGV
			  FROM THAMGIADT TGDT 	
			  JOIN GIAOVIEN GV ON TGDT.MAGV = GV.MAGV) 
		)

--Q48
SELECT DISTINCT GV.*
FROM GIAOVIEN GV, GIAOVIEN GV2
WHERE GV.HOTEN = GV2.HOTEN AND GV.PHAI = GV2.PHAI AND GV.MAGV != GV2.MAGV

--Q49
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG > ANY (SELECT GV.LUONG FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM WHERE BM.TENBM = N'Công nghệ phần mềm')

--Q50
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.LUONG > ANY (SELECT MAX(GV.LUONG) FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM WHERE BM.TENBM = N'Hệ thống thông tin')

--Q51
SELECT K.MAKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
			   	 JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
GROUP BY K.MAKHOA
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM
GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
			JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
GROUP BY K.MAKHOA)

--Q52
SELECT GVCNDT
FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT)

--Q53
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM GIAOVIEN GROUP BY MABM)

--Q54
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM, TGDT.MADT
HAVING COUNT(*) >= ALL (
SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM, TGDT.MADT)

--Q55
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
WHERE BM.MABM = 'HTTT'
GROUP BY GV.HOTEN, BM.TENBM, TGDT.MADT
HAVING COUNT(*) >= ALL (
SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
WHERE BM.MABM = 'HTTT'
GROUP BY GV.HOTEN, BM.TENBM, TGDT.MADT)

--Q56
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN NGUOITHAN NT ON NT.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM, NT.MAGV
HAVING COUNT(*) >= ALL (
SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
				 JOIN NGUOITHAN NT ON NT.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM, NT.MAGV)

--Q57
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
				 JOIN DETAI DT ON DT.GVCNDT = BM.TRUONGBM
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(*) >= ALL (
SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
				 JOIN DETAI DT ON DT.GVCNDT = BM.TRUONGBM
GROUP BY GV.HOTEN, GV.MAGV
)