--w6
--Q58
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE NOT EXISTS (
SELECT MADT FROM DETAI
EXCEPT
(SELECT MADT FROM THAMGIADT TGDT2 
WHERE TGDT2.MAGV = TGDT.MAGV)
)

--Q59
SELECT DISTINCT DT.TENDT
FROM THAMGIADT TGDT JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE NOT EXISTS (
SELECT MAGV FROM GIAOVIEN WHERE MABM = 'HTTT'
EXCEPT(
SELECT TGDT2.MAGV FROM THAMGIADT TGDT2 JOIN DETAI DT2 ON TGDT2.MADT = DT2.MADT
WHERE TGDT.MADT = TGDT2.MADT)
)

--Q60
SELECT DISTINCT DT.TENDT
FROM THAMGIADT TGDT JOIN DETAI DT ON TGDT.MADT = DT.MADT

WHERE NOT EXISTS (
SELECT MAGV FROM GIAOVIEN WHERE MABM = 'HTTT'
EXCEPT(
SELECT TGDT2.MAGV FROM THAMGIADT TGDT2 JOIN DETAI DT2 ON TGDT2.MADT = DT2.MADT
WHERE TGDT.MADT = TGDT2.MADT)
)

--Q61
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE NOT EXISTS (
SELECT DT.MADT FROM DETAI DT WHERE DT.MACD  = 'QLGD'
EXCEPT(
SELECT TGDT2.MADT
FROM GIAOVIEN GV2 JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
WHERE GV.MAGV = GV2.MAGV)
)
--SUS

--Q62
SELECT DISTINCT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE NOT EXISTS (
SELECT _TGDT.MADT FROM THAMGIADT _TGDT JOIN GIAOVIEN _GV ON _GV.MAGV = _TGDT.MAGV 
WHERE _GV.HOTEN = N'Trần Trà Hương'
EXCEPT(
SELECT TGDT2.MADT
FROM GIAOVIEN GV2 JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
WHERE GV.MAGV = GV2.MAGV)
) AND GV.HOTEN != N'Trần Trà Hương'

--Q63
SELECT DISTINCT DT.TENDT
FROM THAMGIADT TGDT JOIN DETAI DT ON TGDT.MADT = DT.MADT
					JOIN GIAOVIEN GV ON GV.MAGV = TGDT.MAGV
WHERE MABM = 'HHC' AND NOT EXISTS (
SELECT MAGV FROM GIAOVIEN WHERE MABM = 'HHC'
EXCEPT(
SELECT TGDT2.MAGV FROM THAMGIADT TGDT2 JOIN DETAI DT2 ON TGDT2.MADT = DT2.MADT
JOIN GIAOVIEN GV2 ON GV2.MAGV = TGDT2.MAGV
WHERE TGDT.MADT = TGDT2.MADT)
)

--Q64
--CÁCH 1: EXCEPT (SAI VÌ CÓ THÊM 0024)
SELECT DISTINCT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
				 JOIN CONGVIEC CV ON TGDT.MADT = CV.MADT
WHERE NOT EXISTS (
SELECT DISTINCT _CV.TENCV FROM THAMGIADT _TGDT JOIN GIAOVIEN _GV ON _GV.MAGV = _TGDT.MAGV
											   JOIN CONGVIEC _CV ON _TGDT.MADT = _CV.MADT
WHERE _CV.MADT = '006'
EXCEPT(
SELECT DISTINCT CV2.TENCV
FROM GIAOVIEN GV2 JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
				  JOIN CONGVIEC CV2 ON TGDT2.MADT = CV2.MADT
WHERE GV.MAGV = GV2.MAGV AND CV2.MADT = CV.MADT)
) 

--CÁCH 3: COUNT
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE TGDT.MADT = '006'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(TGDT.MADT) = (
	SELECT COUNT(MADT) FROM CONGVIEC 
	WHERE MADT = '006'
)

--Q65
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
WHERE NOT EXISTS (
SELECT DT.MADT FROM DETAI DT WHERE DT.MACD  = N'ƯDCN'
EXCEPT(
SELECT TGDT2.MADT
FROM GIAOVIEN GV2 JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
WHERE GV.MAGV = GV2.MAGV)
)

--Q66
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE NOT EXISTS (
SELECT _DT.MADT FROM DETAI _DT JOIN GIAOVIEN _GV ON _DT.GVCNDT = _GV.MAGV
WHERE _GV.HOTEN = N'Trần Trà Hương'
EXCEPT(
SELECT TGDT2.MADT
FROM GIAOVIEN GV2 JOIN THAMGIADT TGDT2 ON GV2.MAGV = TGDT2.MAGV
WHERE GV.MAGV = GV2.MAGV)
)

--Q67
SELECT DISTINCT DT.TENDT
FROM THAMGIADT TGDT JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE NOT EXISTS (
SELECT _GV.MAGV FROM GIAOVIEN _GV JOIN THAMGIADT _TGDT ON _GV.MAGV = _TGDT.MAGV
								  JOIN BOMON _BM ON _BM.MABM = _GV.MABM
								  JOIN KHOA _K ON _K.MAKHOA = _BM.MAKHOA
WHERE _K.MAKHOA = 'CNTT'
EXCEPT(
SELECT TGDT2.MAGV FROM THAMGIADT TGDT2 JOIN DETAI DT2 ON TGDT2.MADT = DT2.MADT
WHERE TGDT.MADT = TGDT2.MADT)
) 

--Q68
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
				 JOIN DETAI DT ON DT.MADT = TGDT.MADT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.HOTEN
HAVING COUNT(DT.MADT) = (
	SELECT COUNT(CV2.MADT) FROM CONGVIEC CV2 JOIN DETAI DT ON DT.MADT = CV2.MADT
	WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
)

--Q69
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
				 JOIN DETAI DT ON DT.MADT = TGDT.MADT
WHERE DT.KINHPHI > 100
GROUP BY GV.HOTEN
HAVING COUNT(TGDT.MADT) = (
	SELECT COUNT(DT.MADT) FROM DETAI DT
	WHERE DT.KINHPHI > 100
)

--Q70 
SELECT DISTINCT DT.TENDT
FROM THAMGIADT TGDT JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE NOT EXISTS (
SELECT _GV.MAGV FROM GIAOVIEN _GV JOIN THAMGIADT _TGDT ON _GV.MAGV = _TGDT.MAGV
								  JOIN BOMON _BM ON _BM.MABM = _GV.MABM
								  JOIN KHOA _K ON _K.MAKHOA = _BM.MAKHOA
WHERE _K.TENKHOA = N'Sinh học'
EXCEPT(
SELECT TGDT2.MAGV FROM THAMGIADT TGDT2 JOIN DETAI DT2 ON TGDT2.MADT = DT2.MADT
WHERE TGDT.MADT = TGDT2.MADT)
) 

--Q71
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
				 JOIN CONGVIEC CV ON TGDT.MADT = CV.MADT
				 JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(CV.SOTT) = (
	SELECT COUNT(SOTT) FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
	WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
)

--Q72
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.MABM, GV.GVQLCM
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
				 JOIN CONGVIEC CV ON TGDT.MADT = CV.MADT
				 JOIN DETAI DT ON TGDT.MADT = DT.MADT
WHERE DT.MACD = 'NCPT'
GROUP BY GV.MAGV, GV.HOTEN, GV.MABM, GV.GVQLCM
HAVING COUNT(DT.MADT) = (
	SELECT COUNT(DT.MADT) FROM DETAI DT 
	WHERE DT.MACD = 'NCPT'
)