--vd3: input: @magv, output: @hoten, @tenbomon, @tenkhoa
create proc sp_timInfoGV @magv char(10),
						 @hoten nvarchar(100) out,
						 @tenbomon nvarchar(50) out,
						 @tenkhoa nvarchar(50) out
as
	select @hoten = gv.HOTEN, @tenbomon = bm.TENBM, @tenkhoa = k.TENKHOA
	from GIAOVIEN gv join BOMON bm on gv.MABM = bm.MABM
					 join KHOA k on bm.MAKHOA = k.MAKHOA
	where gv.MAGV = @magv
go
declare @ht nvarchar(100), @tbm nvarchar(50), @tk nvarchar(50)
exec sp_timInfoGV '001', @ht out, @tbm out, @tk out
select @ht N'Họ tên', @tbm N'Tên bộ môn', @tk N'Tên khoa'

--vd3: tạo sp nhập vào mã khoa, trả ra số lượng gv của khoa có tham gia đề tài
--dúng return trả ra mã thực thi
--0 không tồn tại khoa
--1 có khoa có mã cần tìm
--viết lệnh thực thi
create or alter proc sp_timGVinK @makhoa char(10),
						@magv char(10),
						@slgv int out
as 
	select @slgv = count(distinct @magv)
	from GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
					 JOIN BOMON BM ON BM.MABM = GV.MABM
					 JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
	group by k.MAKHOA
go 
declare @sl int 
exec sp_timGVinK 'CNTT', @sl out 

--a
CREATE PROC SP_HELLOWORLD 
AS
BEGIN
	PRINT 'Hello World !!!'
END
GO
EXEC SP_HELLOWORLD

--B
CREATE OR ALTER PROC SP_INTONG2SO @a INT, @b INT
AS
	PRINT @a + @b;
GO
EXEC SP_INTONG2SO 2, 3

--C
CREATE OR ALTER PROC SP_TONG2SO @a INT, @b INT, @sum INT OUT
AS
	SET @sum = @a + @b;

DECLARE @TONG INT
EXEC SP_TONG2SO 2, 4, @TONG OUT
PRINT @TONG

--D
CREATE OR ALTER PROC SP_INTONG3SO @a INT, @b INT, @c INT
AS
BEGIN
	DECLARE @SUM1 INT, @SUM2 INT
	EXEC SP_TONG2SO @a, @b, @SUM1 OUT
	EXEC SP_TONG2SO @SUM1, @C, @SUM2 OUT
	PRINT @SUM2
END
GO
EXEC SP_INTONG3SO 3,4,5

--e
CREATE OR ALTER PROC SP_TONGMN @M INT, @N INT
AS
	DECLARE @I INT, @SUM INT
	SET @I = @M
	SET @SUM = 0
	WHILE(@I <= @N)
	BEGIN
		SET @SUM = @SUM + @I
		SET @I = @I + 1
	END 
	PRINT @SUM
GO
EXEC SP_TONGMN 3, 5

--f
CREATE OR ALTER PROC SP_ISPRIME @N INT
AS 
	DECLARE @I INT, @RES INT
	SET @RES = 1
	IF (@N <= 2)
		SET @RES = 0
	SET @I = 2
	WHILE (@I <= SQRT(@N))
	BEGIN
	IF (@N % @I = 0)
		BEGIN
			SET @RES = 0
			BREAK
		END
	SET @I = @I + 1
	END
	RETURN @RES

DECLARE @CHECK INT
EXEC @CHECK = SP_ISPRIME 4
PRINT @CHECK

--G
CREATE OR ALTER PROC SP_SUMOFPRIME @M INT, @N INT
AS
	DECLARE @SUM INT, @I INT, @CHECK INT
	SET @SUM = 0
	SET @I = @M
	WHILE (@I <= @N)
	BEGIN
		EXEC @CHECK = SP_ISPRIME @I
		IF (@CHECK = 1)
			BEGIN
			PRINT @I 
			SET @SUM = @SUM + @I
			END
		SET @I = @I + 1
	END 
	PRINT @SUM
GO
EXEC SP_SUMOFPRIME 1, 5

--H
CREATE OR ALTER PROC SP_GCD @M INT, @N INT, @RES INT OUT
AS
	SET @RES = 1
	IF (@M = 0 OR @N = 0)
		SET @RES = @N + @M
	WHILE(@M != @N)
	BEGIN
		IF (@M > @N)
			SET @M = @M - @N
		ELSE SET @N = @N - @M
	END
	SET @RES = @N
	RETURN @RES
GO
DECLARE @RES INT 
EXEC SP_GCD 16, 30, @RES OUT
PRINT @RES

--I
CREATE OR ALTER PROC SP_BCNN @M INT, @N INT
AS
	DECLARE @RES INT, @GCD INT
	EXEC SP_GCD @M, @N, @GCD OUT
	SET @RES = @N * @M / @GCD
	PRINT @RES
GO
EXEC SP_BCNN 2022, 30

--J
CREATE OR ALTER PROC SP_J
AS
BEGIN
    SELECT * FROM GIAOVIEN
END
GO

EXEC SP_J

--K
CREATE OR ALTER PROC SP_K
AS
BEGIN
	SELECT GV.MAGV, GV.HOTEN, COUNT(MADT) 'SODT'
	FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
	GROUP BY GV.MAGV, GV.HOTEN
END
GO
EXEC SP_K

--L
CREATE OR ALTER PROC SP_L @MAGV CHAR(5)
AS
BEGIN
	IF(EXISTS(SELECT * FROM GIAOVIEN WHERE MAGV = @MAGV))
		PRINT N'Tồn tại'
	ELSE PRINT N'Không tồn tại'
END
GO
EXEC SP_M '0013'

--M
CREATE OR ALTER PROC SP_M @MAGV CHAR(5)
AS
BEGIN
	DECLARE @TEN NVARCHAR(50), @SLDT INT, @SLNT INT
	SELECT @TEN = GV.HOTEN, @SLDT = COUNT(MADT)
	FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
	WHERE @MAGV = GV.MAGV
	GROUP BY GV.MAGV, GV.HOTEN
	SELECT @SLNT = COUNT(NT.MAGV)
	FROM NGUOITHAN NT 
	WHERE NT.MAGV = @MAGV
	PRINT @MAGV + CAST(@SLDT AS CHAR(5)) + CAST(@SLNT AS CHAR(5))
END
GO
EXEC SP_M '001'

--N
CREATE OR ALTER PROC SP_N @MAGV CHAR(5), @MADT CHAR(5)
AS
BEGIN
	DECLARE @CHECK BIT
	SET @CHECK = 1
	SELECT @CHECK = CASE WHEN EXISTS (
		SELECT *
		FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
						 JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
		WHERE GV.MAGV = @MAGV AND @MADT = TGDT.MADT
		)
	THEN 1 ELSE 0 END
	IF @CHECK = 1
	PRINT 'OK'
	ELSE PRINT 'NOT OK'
	RETURN @CHECK
END
GO
EXEC SP_N '002', '001'

--O
CREATE OR ALTER PROC SP_O @MAGV CHAR(5), @MADT CHAR(5), @STT INT
AS
BEGIN
    SET NOCOUNT ON; --KHỎI IN RA DÒNG BAO NHIÊU ROW AFFECTED

    -- KTRA CÓ GV O
    IF NOT EXISTS (SELECT * FROM GIAOVIEN WHERE MAGV = @MAGV)
        RETURN -1;
    -- KTRA CÓ CV O
    IF NOT EXISTS (SELECT * FROM CONGVIEC WHERE MADT = @MADT AND SOTT = @STT)
        RETURN -2;
    -- KTRA THGIAN CÓ > 0 O
    IF NOT EXISTS (
        SELECT 1 FROM CONGVIEC 
        WHERE MADT = @MADT AND SOTT = @STT AND DATEDIFF(DAY, NGAYBD, NGAYKT) > 0
    )
        RETURN -3
    -- KTRA CÂU N
    DECLARE @CHECK_N INT
    EXEC @CHECK_N = SP_N @MAGV, @MADT
    IF (@CHECK_N = 0)
        RETURN -4
    ELSE
    BEGIN
        -- THÊM 
        INSERT THAMGIADT (MAGV, MADT, STT)
        VALUES (@MAGV, @MADT, @STT)
        RETURN 0
    END
END
GO
EXEC SP_O '002', '002', 3
SELECT * FROM THAMGIADT
DELETE FROM THAMGIADT
WHERE MADT = '001' AND MAGV = '002' AND STT = 3
SELECT * FROM THAMGIADT

--P
CREATE OR ALTER PROC SP_P @MAGV CHAR(5)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM GIAOVIEN WHERE @MAGV = MAGV)
		RETURN -1
	IF EXISTS (SELECT * 
			   FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
			   WHERE @MAGV = GV.MAGV)
		RETURN -2
	IF EXISTS (SELECT * 
			   FROM GIAOVIEN GV JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
			   WHERE @MAGV = GV.MAGV)
		RETURN -3
	ELSE
	BEGIN
		DELETE FROM GIAOVIEN
		WHERE MAGV = @MAGV
		RETURN 0
	END
END
GO 
--INSERT GIAOVIEN(MAGV)
--VALUES('988')
SELECT * FROM GIAOVIEN
DECLARE @CHECK INT
EXEC @CHECK = SP_P '999'
PRINT @CHECK
SELECT * FROM GIAOVIEN

--Q
CREATE OR ALTER PROC SP_Q @MABM CHAR(5)
AS
	SELECT GV1.MAGV, GV1.HOTEN, COUNT(DISTINCT TGDT.MADT) 'SLDT', COUNT(DISTINCT NT.TEN) 'SLNT',
			COUNT(DISTINCT GV2.MAGV) 'SLGVQL'
	FROM GIAOVIEN GV1 LEFT JOIN THAMGIADT TGDT ON TGDT.MAGV = GV1.MAGV
					  LEFT JOIN NGUOITHAN NT ON NT.MAGV = GV1.MAGV
					  LEFT JOIN GIAOVIEN GV2 ON GV1.MAGV = GV2.GVQLCM
	WHERE GV1.MABM = @MABM
	GROUP BY GV1.MABM, GV1.HOTEN, GV1.MAGV
GO
EXEC SP_Q 'HTTT'
--R
CREATE OR ALTER PROC SP_R @MAGVA CHAR(5), @MAGVB CHAR(5)
AS
	IF (@MAGVA = (SELECT BM.TRUONGBM 
				  FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM WHERE GV.MAGV = @MAGVB)
		AND (SELECT GV.LUONG FROM GIAOVIEN GV WHERE GV.MAGV = @MAGVA) <  (SELECT GV.LUONG FROM dbo.GIAOVIEN GV WHERE GV.MAGV = @MAGVB))
		PRINT N'Lương của' + @MAGVA + ' và ' + @MAGVB + N'có sự sai sót chiếu theo quy định!'
	IF (@MAGVB = (SELECT BM.TRUONGBM 
				  FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM WHERE GV.MAGV = @MAGVA)
		AND (SELECT GV.LUONG FROM GIAOVIEN GV WHERE GV.MAGV = @MAGVB) <  (SELECT GV.LUONG FROM GIAOVIEN GV WHERE GV.MAGV = @MAGVA))
		PRINT N'Lương của' + @MAGVA + ' và ' + @MAGVB + N'có sự sai sót chiếu theo quy định!'
	ELSE
		PRINT N'Không vi phạm'
GO
EXEC SP_R '004', '005'

--S
CREATE OR ALTER PROC SP_S @MAGV CHAR(5), @TEN NVARCHAR(50), @BOD DATE, @LUONG INT
AS 
BEGIN 
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE @MAGV = MAGV)
		RETURN -1
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE @TEN = HOTEN)
		RETURN -2
	IF EXISTS (SELECT * FROM GIAOVIEN WHERE DATEDIFF(YEAR, 2024, @BOD) < 18)
		RETURN -3
	IF (@LUONG < 0)
		RETURN -4
	INSERT GIAOVIEN(MAGV, HOTEN, NGSINH, LUONG)
	VALUES (@MAGV, @TEN, @BOD, @LUONG)
END
GO 
EXEC SP_S '001', N'BUU', '1999/09/02', 1000000
SELECT * FROM GIAOVIEN
DELETE FROM GIAOVIEN
WHERE MAGV = '111'

--T
CREATE OR ALTER PROC SP_T
AS
BEGIN
	DECLARE @NEXT CHAR(5)
	DECLARE @MAXCODE INT
	SELECT @NEXT = MIN(MAGV)
    FROM (
        SELECT 
            RIGHT('00' + CAST(CAST(SUBSTRING(MAGV, 2, LEN(MAGV)) AS INT) + 1 AS VARCHAR(3)), 3) AS MAGV
        FROM 
            GIAOVIEN 
        EXCEPT
        SELECT 
            MAGV
        FROM 
            GIAOVIEN
    ) AS CODES
	INSERT GIAOVIEN(MAGV)
	VALUES (@NEXT)
END
GO
--INSERT GIAOVIEN(MAGV)
--VALUES ('013')
EXEC SP_T
SELECT * FROM GIAOVIEN
--XÓA 
DELETE FROM GIAOVIEN
WHERE CAST(MAGV AS INT) > 10

