--mssv: 22127405
--họ tên: Trần Minh Thư
--CÂU 1
SELECT BM.MABM, BM.TENBM
FROM BOMON BM JOIN GIAOVIEN GV ON GV.MABM = BM.MABM
			  JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
			  JOIN CONGVIEC CV ON CV.SOTT = TGDT.STT
WHERE CV.TENCV LIKE '%Phân tích%'
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(distinct GV.MAGV) >= ALL(SELECT COUNT(distinct GV.MAGV) 
			  FROM BOMON BM JOIN GIAOVIEN GV ON GV.MABM = BM.MABM
			  JOIN THAMGIADT TGDT ON TGDT.MAGV = GV.MAGV
			  JOIN CONGVIEC CV ON CV.SOTT = TGDT.STT
WHERE CV.TENCV LIKE '%Phân tích%')

--CÂU 2  GV.MAGV, GV.HOTEN
--cách khác:
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA
WHERE K.MAKHOA IN
(SELECT BM.MAKHOA
FROM BOMON BM 
GROUP BY BM.MAKHOA
HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(MABM)
							FROM BOMON GROUP BY MAKHOA)
)
OR K.MAKHOA IN
(SELECT BM.MAKHOA
FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV = DT.GVCNDT
			  JOIN BOMON BM ON CN.MABM = BM.MABM
GROUP BY BM.MAKHOA
HAVING COUNT(DISTINCT DT.GVCNDT) >= ALL(SELECT COUNT(DISTINCT DT.GVCNDT)
FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV = DT.GVCNDT
			  JOIN BOMON BM ON CN.MABM = BM.MABM
GROUP BY BM.MAKHOA)
)

--CÂU 3
SELECT DT.MADT, DT.TENDT, DT.CAPQL, DT.KINHPHI, COUNT(CV.SOTT) 'SLCV'
FROM DETAI DT LEFT JOIN CONGVIEC CV ON DT.MADT = CV.MADT
WHERE DT.KINHPHI >= ALL(SELECT DT2.KINHPHI 
						FROM DETAI DT2
						WHERE DT2.CAPQL = DT.CAPQL)
GROUP BY DT.MADT, DT.TENDT, DT.CAPQL, DT.KINHPHI

--CÂU 4
SELECT GV.*
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN BOMON BM ON BM.MABM = GV.MABM
				 JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
				 JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE K.MAKHOA = 'CNTT' AND NOT EXISTS(
SELECT DT.MADT
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
				 JOIN BOMON BM ON BM.MABM = GV.MABM
				 JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
				 JOIN DETAI DT ON DT.MADT = TG.MADT
				 JOIN GIAOVIEN CN ON DT.GVCNDT = CN.MAGV
WHERE K.MAKHOA = 'CNTT' AND DT.CAPQL = N'Trường'
EXCEPT(
	SELECT TGDT.MADT
	FROM dbo.THAMGIADT TGDT
	WHERE TGDT.MAGV = GV.MAGV
)
)
--chưa xong

--CÂU 5
CREATE OR ALTER PROC SP_XOATGDT @MAGV CHAR(5), @MADT CHAR(5), @STT INT
AS
--CÔNG VIỆC CHƯA CÓ KQ
	IF((SELECT KETQUA FROM THAMGIADT WHERE @MADT = MADT AND @MAGV = MAGV AND @STT = STT) IS NULL)
		RETURN -1
--THAM GIA DUY NHẤT CỦA GV
	IF((SELECT COUNT(GV.MAGV) FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
		WHERE @MAGV = GV.MAGV AND @MADT = MADT
		GROUP BY GV.MAGV) = 1)
		RETURN -2
--THAM GIA DUY NHẤT CHO DT
	IF((SELECT COUNT(TG.MADT) FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
		WHERE @MAGV = GV.MAGV AND @MADT = MADT
		GROUP BY TG.MADT) = 1)
		RETURN -3
	DELETE FROM THAMGIADT
	WHERE @MAGV = MAGV AND @MADT = MADT AND @STT = STT 
	RETURN 0
GO
INSERT THAMGIADT
VALUES('003','002', 1, 2.0, N'Đạt')
SELECT * FROM THAMGIADT
GO
EXEC SP_XOATGDT '003', '002', 1
--đề thi thck môn csdl
--1
SELECT BM.MABM
FROM BOMON BM JOIN GIAOVIEN GV ON GV.MABM = BM.MABM
			  JOIN GV_DT DT ON DT.MAGV = GV.MAGV
GROUP BY BM.MABM
HAVING COUNT(DISTINCT GV.MAGV) >= ALL(
SELECT COUNT(DISTINCT GV.MAGV)
FROM BOMON BM JOIN GIAOVIEN GV ON GV.MABM = BM.MABM
			  JOIN GV_DT DT ON DT.MAGV = GV.MAGV
GROUP BY BM.MABM)

--2
SELECT T.MAGV
FROM GIAOVIEN T 
WHERE NOT EXISTS (
SELECT DT.MADT
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
WHERE GV.MAGV = N'Trương Nam Sơn' 
EXCEPT(
SELECT R.MADT
FROM THAMGIADT R
WHERE R.MAGV = T.MAGV)) AND T.HOTEN != N'Trương Nam Sơn'

--Tìm xem bộ S nào không thoả mãn T 
--Nếu rỗng --> T thoả mãn tất cả
--Nếu tìm thấy ít nhất một S không thoả T --> T không thoả mãn tất cả
--R là số chia R liên kết với T là kết quả

--3
SELECT DISTINCT GV1.MAGV
FROM GIAOVIEN GV1 JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
WHERE TG.MADT IN(
SELECT TG.MADT
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.KINHPHI >= 80)
GROUP BY GV1.MAGV 
HAVING COUNT (DISTINCT TG.MADT) = (
SELECT COUNT(DISTINCT TG.MADT)
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE GV.MAGV = GV1.MAGV
GROUP BY GV.MAGV 
)

UPDATE DETAI
SET KINHPHI = 15
WHERE MADT = '002'
--SỬA LẠI BẢN CŨ
UPDATE DETAI
SET KINHPHI = 20
WHERE MADT = '002'

--cách tiếp cận khác: chỉ cần dt của nó < 80 => out

SELECT DISTINCT GV1.MAGV
FROM GIAOVIEN GV1 JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
WHERE GV1.MAGV NOT IN(
SELECT TG.MAGV
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.KINHPHI < 20)

--CHỌN MADT LÀ SAI VÌ NẾU 003 CÓ 1 MÃ < 20 VÀ > 20 THÌ NÓ CHỈ LOẠI 003 
--DƯỚI 20 CÒN TRÊN 20 NÓ VẪN LẤY => LẤY LUÔN 003 => MUỐN CHỌN GÌ THÌ 
--CHỌN TRỰC TIẾP, LOẠI TRỰC TIẾP
SELECT DISTINCT GV1.MAGV
FROM GIAOVIEN GV1 JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
WHERE TG.MADT NOT IN(
SELECT TG.MADT
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.KINHPHI < 20)